<?php
/**
 * @file
 * Code for the openlucius_milestone feature.
 */

include_once 'openlucius_milestone.features.inc';
include_once drupal_get_path('module', 'openlucius_milestone') . '/includes/class.inc';

function openlucius_milestone_menu() {
  return array(
    'group-calendar/milestone/list/%' => [
      'title' => t('Milestone List'),
      'page callback' => 'openlucius_milestone_list_page',
      'page arguments' => [3],
      'access arguments' => ['access content'],
      'file' => 'page.inc',
      'file path' => drupal_get_path('module', 'openlucius_milestone') . '/includes'
    ],
    'openlucius-milestone/%node/update' => [
      'page callback'    => 'openlucius_milestone_update_todo',
      'page arguments'   => array(1),
      'access arguments' => array('access content'),
      'file'             => 'includes/page.inc',
      'type'             => MENU_NORMAL_ITEM,
    ]
  );
}

function openlucius_milestone_theme() {
  return [
    'openlucius_milestone_list' => [
      'template' => 'templates/openlucius_milestone_list',
    ]
  ];
}

function openlucius_milestone_form_ol_event_node_form_alter(&$form, &$form_state, $form_id) {
  if($form['field_todo_list_status']) {
    $form['field_todo_list_status']['#access'] = FALSE;
  }
}

function openlucius_milestone_node_presave($node) {
  if ($node->is_new == TRUE) {
    $epic_start = variable_get('openlucius_epics_progress_epic_start_todo_state', '');
    if($epic_start != '') {
      $node->field_todo_list_status[LANGUAGE_NONE] = ['0' => ['tid' => $epic_start]];
    }
  }
}
